MakeContributions/ideahub

data/ideas.json

Hi
This PR to add a Hotel Reservation System Project 
Thanks

Add Hotel-Reservation-System to ideas.json

---

data/projects.json

Hey,
I have added paint with UG in projects.json please review it 
thanks
closes: #5

added Paint With UG

---

CONTRIBUTING.md

Replaced DSA with ideahub and modified url to URL.

Made corrections - DSA to ideahub

---

data/projects.json
docs/DESKTOP_APPLICATION_INTERMEDIATE.md

I have added UG Typing Expert please review it 
Closes: #8 
Thanks

UG Tping Expert

---

data/projects.json

I have added Tic Tac Toe please review it 
closes: #12 
Thanks

added Tic Tac Toe

---

data/projects.json

I have added library management
Please review it 
closes: #17 
Thanks

chore(projects): added library management

---

CONTRIBUTING.md
package-lock.json

Just changed one small line where you are clarifying how to include one's github handle in a clone url

docs: clarification to readme

---

data/projects.json

chore(data): added queue visualizer

---

data/ideas.json
data/projects.json

chore(data): added TravelYaari website

---

data/projects.json

Hey @ming-tsai,
I have added the car zone in projects.json please review it...
closes: #27 
Thanks...

added car zone in projects.json

---

data/ideas.json
data/projects.json

added an idea and project in JSON files

chore: added an idea and project

---

data/ideas.json

chore(ideas): add BackYard Produce Market

---

data/projects.json

I just added a project I have been working on called vision-ai

chore(project): add vision-ai

---

data/ideas.json

Propose an idea of project for the Bafang tribe in Cameroon.

chore(idea): add learning babang application

---

data/ideas.json

chore(idea): add slack clone

---

data/ideas.json

This will be a fun and easy project for beginners

chore(ideas): added Alarm Clock

---

data/projects.json

add poketalog to list project on project.json

chore(projects):  add poketalog

---

data/projects.json

add Kunci Web Scrapper to list project on project.json

chore: add kunci scrapper

---

data/ideas.json

Please review my PR for adding a file organisation project idea

chore(ideas): add file organisations

---

data/projects.json

I have 2 projects built on top of Vue js and thought can be useful for someone to learn from it.

chore(ideas): add sahilpatel personal site and ip tracker

---

data/ideas.json

Added a book-sharing and language translator idea. Please review

docs(ideas): add open library and language translator

---

data/ideas.json

my first contribution to ideahub.

docs(ideas): add RGB-slider web app

---

data/projects.json
docs/WEBSITE_BASIC.md

It's a basic website. I changed in two files one is `projects.json` and another one is `WEBSITE_BASIC.md`.

docs(projects): add e-learning

---

data/ideas.json

I just added an idea on developing a web application with ES6 JavaScript using API from Rapid API.

docs(ideas): add book app

---

data/ideas.json
data/projects.json

Clash of Space game both Idea and Project added

docs: add clash of space idea and project

---

CONTRIBUTING.md

Fixed up wording for CONTRIBUTING.md file so that wording is easier to read.

docs(CONTRIBUTING): make the documentation more easier to read

---

data/ideas.json
data/projects.json

Added my java based desktop application

docs: add an idea and project for file protection system

---

data/projects.json
docs/WEBSITE_BASIC.md

Hey @ming-tsai 
I added the Image Gallery Website please give it a review
It closes #106
Thanks 😄

docs(projects): add image gallery website

---

data/ideas.json
data/projects.json

Hello,
Added idea for Machine Learning model for Image Classification

docs: add guess the number idea and project
